### ISSUE TITLE
Error transferring more than 30 files from Atari to PC with 32MiB virtual disk

### ISSUE THREAD

**Issue by z80andrew** [z80andrew/SerialDisk#22]
I still seem to have this issue with version 2.3.11.0. I try to send some known good files from ST to PC and it crashes after 30 files.
```
grep "Saving local file" log/serial_port_error.log  | wc -l
30
```
Included: verbose log
[serial_port_error.log](https://github.com/z80andrew/SerialDisk/files/5252256/serial_port_error.log)

_Originally posted by @LaurentChardon in https://github.com/z80andrew/SerialDisk/issues/8#issuecomment-695814865_

**Comment by z80andrew** [comment]
The error occurs at `System.IO.Path.Combine`, which suggests an incompatibility with the file path and filename being written to the PC.
Could you let me know what the file path and filename are so I can include it in my tests? I assume it will be something like `SAVED/KSEKA/FILENAME.EXT`. I will also test whether this is a file count issue.

**Comment by LaurentChardon** [comment]
I think that the file being written is `/home/laurent/atari/serialdisk-linux-x64/Atari/SAVED/KSEKA/NOUV_2.BAS`. `NOUV_2.BAS` is the name showing in the copy dialog box on the ST when the error occurs.

I can copy this file no problem when the folder `KSEKA` is empty. When there are already 30 files in it, it fails. 

I can copy all files from the physical disk to a RAM disk and it works fine. If I try to copy the physical disk (or RAM disk) to SerialDisk, it fails like reported here. If I mix-up the order, it fails on another file, at the 31st.

Most (but not all) of the disks that I have behave this way, with the same `Serial port error` from the same trap in the code. When there are folders on the disk, I can still get the error but not after 30 files. I'm not sure that I understand the pattern when there are folders.

The disks were made 35 years ago on a French 520STfm, probably TOS 1.04. I'm reading them with a US 1020STE, not sure the TOS level. 

I'm willing to test if you want to give me things to try. Since there is no sensitive information on the disk, I could make an image of it and send it to you.

**Comment by LaurentChardon** [comment]
Update: I realized that `SERIALDISK.CFG` was not consistent with the settings of `SerialDisk`. Making them consistent, for a 512Mb disk, seems to work.

**Comment by LaurentChardon** [comment]
Before `SERIALDISK.CFG` contained `M5` but `SerialDisk` was run with the default 32MiB disk. I've tried `M5` + `--disk-size 512` and I have no errors anymore. I will try `M1`+ `--disk-size 32` and report.

**Comment by z80andrew** [comment]
The disk size setting in `SERDISK.CFG` specifies a maximum to ensure enough RAM is reserved for the disk buffer, so it shouldn't need to match the `SerialDisk --disk-size` parameter.

Thanks a lot for the additional information. I'll run some tests tomorrow and see if I can reproduce the error.

**Comment by LaurentChardon** [comment]
It fails with a 32MiB disk but not a 512MiB. That's too bad, because the smaller drive is MUCH faster that the larger one!
Thanks for your time looking into this!

**Comment by z80andrew** [comment]
Bug reproduced on win10-x64 / SerialDisk v2.4. 

`System.IO.Path.Combine` fails because the directory name entry for the given cluster is null after 30 entries (1 cluster).

**Comment by z80andrew** [comment]
I've tested the fix with folders containing 30 files and 60 files with success. I'll do further testing along with performance monitoring over the next few days with a view to releasing a beta at the weekend.

**Comment by LaurentChardon** [comment]
I gave version_2.5 a try and it seems to work well. I had trouble compiling initially because the version string in the csproj file contains spaces, which I think is not allowed, but once that fixed it worked perfectly. Thank you!

**Comment by z80andrew** [comment]
That's an interesting note about the compilation issue; I have no problems compiling with Visual Studio 2019. AssemblyVersion and FileVersion cannot have spaces, but the Version/InformationallVersion attribute should accept them as far as I'm aware. I'll check whether this affects the automated builds.

Thanks for testing - Great to hear the fix worked for you 👍

**Comment by z80andrew** [comment]
Broken after refactor in issue #33
